# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/admin/contestant_instances.proto

require 'google/protobuf'

require 'isuxportal/resources/contestant_instance_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/admin/contestant_instances.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.admin.ListContestantInstancesQuery" do
      optional :team_id, :int64, 1
    end
    add_message "isuxportal.proto.services.admin.ListContestantInstancesResponse" do
      repeated :contestant_instances, :message, 1, "isuxportal.proto.resources.ContestantInstance"
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Admin
        ListContestantInstancesQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.ListContestantInstancesQuery").msgclass
        ListContestantInstancesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.ListContestantInstancesResponse").msgclass
      end
    end
  end
end
