# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/admin/dashboard.proto

require 'google/protobuf'

require 'isuxportal/resources/leaderboard_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/admin/dashboard.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.admin.DashboardRequest" do
    end
    add_message "isuxportal.proto.services.admin.DashboardResponse" do
      optional :leaderboard, :message, 1, "isuxportal.proto.resources.Leaderboard"
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Admin
        DashboardRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.DashboardRequest").msgclass
        DashboardResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.DashboardResponse").msgclass
      end
    end
  end
end
