# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/admin/dashboard.proto

require 'google/protobuf'

require 'isuxportal/resources/leaderboard_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/admin/dashboard.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.admin.DashboardQuery" do
    end
    add_message "isuxportal.proto.services.admin.DashboardResponse" do
      optional :leaderboard, :message, 1, "isuxportal.proto.resources.Leaderboard"
      optional :earliest_unanswered_clarification_at, :message, 2, "google.protobuf.Timestamp"
      optional :unanswered_clarification_count, :int64, 3
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Admin
        DashboardQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.DashboardQuery").msgclass
        DashboardResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.DashboardResponse").msgclass
      end
    end
  end
end
