# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/admin/env_checks.proto

require 'google/protobuf'

require 'isuxportal/resources/env_check_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/admin/env_checks.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.admin.ListEnvChecksQuery" do
      optional :team_id, :int64, 1
    end
    add_message "isuxportal.proto.services.admin.ListEnvChecksResponse" do
      repeated :env_checks, :message, 1, "isuxportal.proto.resources.EnvCheck"
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Admin
        ListEnvChecksQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.ListEnvChecksQuery").msgclass
        ListEnvChecksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.ListEnvChecksResponse").msgclass
      end
    end
  end
end
