# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/admin/leaderboard_dump.proto

require 'google/protobuf'

require 'isuxportal/resources/contestant_instance_pb'
require 'isuxportal/resources/leaderboard_pb'
require 'isuxportal/resources/team_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/admin/leaderboard_dump.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.admin.GetLeaderboardDumpQuery" do
      optional :when, :string, 1
    end
    add_message "isuxportal.proto.services.admin.GetLeaderboardDumpResponse" do
      repeated :items, :message, 1, "isuxportal.proto.services.admin.GetLeaderboardDumpResponse.LeaderboardDumpItem"
    end
    add_message "isuxportal.proto.services.admin.GetLeaderboardDumpResponse.LeaderboardDumpItem" do
      optional :position, :int64, 1
      optional :team, :message, 2, "isuxportal.proto.resources.Team"
      optional :best_score, :message, 3, "isuxportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore"
      optional :latest_score, :message, 4, "isuxportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore"
      optional :target, :message, 5, "isuxportal.proto.resources.ContestantInstance"
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Admin
        GetLeaderboardDumpQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetLeaderboardDumpQuery").msgclass
        GetLeaderboardDumpResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetLeaderboardDumpResponse").msgclass
        GetLeaderboardDumpResponse::LeaderboardDumpItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetLeaderboardDumpResponse.LeaderboardDumpItem").msgclass
      end
    end
  end
end
