# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/admin/teams.proto

require 'google/protobuf'

require 'isuxportal/resources/team_pb'
require 'isuxportal/resources/contestant_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/admin/teams.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.admin.ListTeamsQuery" do
    end
    add_message "isuxportal.proto.services.admin.ListTeamsResponse" do
      repeated :teams, :message, 1, "isuxportal.proto.services.admin.ListTeamsResponse.TeamListItem"
    end
    add_message "isuxportal.proto.services.admin.ListTeamsResponse.TeamListItem" do
      optional :team_id, :int64, 1
      optional :name, :string, 2
      repeated :member_names, :string, 3
      optional :final_participation, :bool, 4
      optional :is_student, :bool, 5
      optional :withdrawn, :bool, 6
      optional :disqualified, :bool, 7
      optional :hidden, :bool, 8
    end
    add_message "isuxportal.proto.services.admin.GetTeamQuery" do
      optional :id, :int64, 1
    end
    add_message "isuxportal.proto.services.admin.GetTeamResponse" do
      optional :team, :message, 1, "isuxportal.proto.resources.Team"
    end
    add_message "isuxportal.proto.services.admin.UpdateTeamQuery" do
      optional :id, :int64, 1
    end
    add_message "isuxportal.proto.services.admin.UpdateTeamRequest" do
      optional :team, :message, 1, "isuxportal.proto.resources.Team"
      repeated :contestants, :message, 2, "isuxportal.proto.resources.Contestant"
    end
    add_message "isuxportal.proto.services.admin.UpdateTeamResponse" do
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Admin
        ListTeamsQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.ListTeamsQuery").msgclass
        ListTeamsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.ListTeamsResponse").msgclass
        ListTeamsResponse::TeamListItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.ListTeamsResponse.TeamListItem").msgclass
        GetTeamQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetTeamQuery").msgclass
        GetTeamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetTeamResponse").msgclass
        UpdateTeamQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.UpdateTeamQuery").msgclass
        UpdateTeamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.UpdateTeamRequest").msgclass
        UpdateTeamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.UpdateTeamResponse").msgclass
      end
    end
  end
end
