// source: isuxportal/resources/contestant_instance.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var isuxportal_resources_team_pb = require('../../isuxportal/resources/team_pb.js');
goog.object.extend(proto, isuxportal_resources_team_pb);
goog.exportSymbol('proto.isuxportal.proto.resources.ContestantInstance', null, global);
goog.exportSymbol('proto.isuxportal.proto.resources.ContestantInstance.Status', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.resources.ContestantInstance = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.isuxportal.proto.resources.ContestantInstance, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.resources.ContestantInstance.displayName = 'proto.isuxportal.proto.resources.ContestantInstance';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.resources.ContestantInstance.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.resources.ContestantInstance} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.resources.ContestantInstance.toObject = function(includeInstance, msg) {
  var f, obj = {
    cloudId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    teamId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    number: jspb.Message.getFieldWithDefault(msg, 3, 0),
    publicIpv4Address: jspb.Message.getFieldWithDefault(msg, 4, ""),
    privateIpv4Address: jspb.Message.getFieldWithDefault(msg, 5, ""),
    status: jspb.Message.getFieldWithDefault(msg, 6, 0),
    team: (f = msg.getTeam()) && isuxportal_resources_team_pb.Team.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.resources.ContestantInstance}
 */
proto.isuxportal.proto.resources.ContestantInstance.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.resources.ContestantInstance;
  return proto.isuxportal.proto.resources.ContestantInstance.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.resources.ContestantInstance} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.resources.ContestantInstance}
 */
proto.isuxportal.proto.resources.ContestantInstance.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCloudId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTeamId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumber(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublicIpv4Address(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrivateIpv4Address(value);
      break;
    case 6:
      var value = /** @type {!proto.isuxportal.proto.resources.ContestantInstance.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 16:
      var value = new isuxportal_resources_team_pb.Team;
      reader.readMessage(value,isuxportal_resources_team_pb.Team.deserializeBinaryFromReader);
      msg.setTeam(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.resources.ContestantInstance.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.resources.ContestantInstance} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.resources.ContestantInstance.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCloudId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTeamId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getNumber();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getPublicIpv4Address();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPrivateIpv4Address();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getTeam();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      isuxportal_resources_team_pb.Team.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.isuxportal.proto.resources.ContestantInstance.Status = {
  UNKNOWN: 0,
  PENDING: 1,
  MODIFYING: 2,
  STOPPED: 3,
  RUNNING: 4,
  TERMINATED: 5
};

/**
 * optional string cloud_id = 1;
 * @return {string}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.getCloudId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.resources.ContestantInstance} returns this
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.setCloudId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 team_id = 2;
 * @return {number}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.getTeamId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.isuxportal.proto.resources.ContestantInstance} returns this
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.setTeamId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 number = 3;
 * @return {number}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.getNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.isuxportal.proto.resources.ContestantInstance} returns this
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.setNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string public_ipv4_address = 4;
 * @return {string}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.getPublicIpv4Address = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.resources.ContestantInstance} returns this
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.setPublicIpv4Address = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string private_ipv4_address = 5;
 * @return {string}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.getPrivateIpv4Address = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.resources.ContestantInstance} returns this
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.setPrivateIpv4Address = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Status status = 6;
 * @return {!proto.isuxportal.proto.resources.ContestantInstance.Status}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.getStatus = function() {
  return /** @type {!proto.isuxportal.proto.resources.ContestantInstance.Status} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.isuxportal.proto.resources.ContestantInstance.Status} value
 * @return {!proto.isuxportal.proto.resources.ContestantInstance} returns this
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional Team team = 16;
 * @return {?proto.isuxportal.proto.resources.Team}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.getTeam = function() {
  return /** @type{?proto.isuxportal.proto.resources.Team} */ (
    jspb.Message.getWrapperField(this, isuxportal_resources_team_pb.Team, 16));
};


/**
 * @param {?proto.isuxportal.proto.resources.Team|undefined} value
 * @return {!proto.isuxportal.proto.resources.ContestantInstance} returns this
*/
proto.isuxportal.proto.resources.ContestantInstance.prototype.setTeam = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.isuxportal.proto.resources.ContestantInstance} returns this
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.clearTeam = function() {
  return this.setTeam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.isuxportal.proto.resources.ContestantInstance.prototype.hasTeam = function() {
  return jspb.Message.getField(this, 16) != null;
};


goog.object.extend(exports, proto.isuxportal.proto.resources);
