// source: resources/contestant.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.isuxportal.proto.resources.Contestant', null, global);
goog.exportSymbol('proto.isuxportal.proto.resources.Contestant.ContestantDetail', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.resources.Contestant = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.isuxportal.proto.resources.Contestant, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.resources.Contestant.displayName = 'proto.isuxportal.proto.resources.Contestant';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.isuxportal.proto.resources.Contestant.ContestantDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.resources.Contestant.ContestantDetail.displayName = 'proto.isuxportal.proto.resources.Contestant.ContestantDetail';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.resources.Contestant.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.resources.Contestant.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.resources.Contestant} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.resources.Contestant.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    teamId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    avatarUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    contestantDetail: (f = msg.getContestantDetail()) && proto.isuxportal.proto.resources.Contestant.ContestantDetail.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.resources.Contestant}
 */
proto.isuxportal.proto.resources.Contestant.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.resources.Contestant;
  return proto.isuxportal.proto.resources.Contestant.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.resources.Contestant} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.resources.Contestant}
 */
proto.isuxportal.proto.resources.Contestant.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTeamId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatarUrl(value);
      break;
    case 7:
      var value = new proto.isuxportal.proto.resources.Contestant.ContestantDetail;
      reader.readMessage(value,proto.isuxportal.proto.resources.Contestant.ContestantDetail.deserializeBinaryFromReader);
      msg.setContestantDetail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.resources.Contestant.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.resources.Contestant.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.resources.Contestant} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.resources.Contestant.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getTeamId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAvatarUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getContestantDetail();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.isuxportal.proto.resources.Contestant.ContestantDetail.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.resources.Contestant.ContestantDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.resources.Contestant.ContestantDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    githubLogin: jspb.Message.getFieldWithDefault(msg, 1, ""),
    discordTag: jspb.Message.getFieldWithDefault(msg, 2, ""),
    isStudent: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.resources.Contestant.ContestantDetail}
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.resources.Contestant.ContestantDetail;
  return proto.isuxportal.proto.resources.Contestant.ContestantDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.resources.Contestant.ContestantDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.resources.Contestant.ContestantDetail}
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGithubLogin(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscordTag(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsStudent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.resources.Contestant.ContestantDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.resources.Contestant.ContestantDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGithubLogin();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDiscordTag();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIsStudent();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional string github_login = 1;
 * @return {string}
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.prototype.getGithubLogin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.resources.Contestant.ContestantDetail} returns this
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.prototype.setGithubLogin = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string discord_tag = 2;
 * @return {string}
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.prototype.getDiscordTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.resources.Contestant.ContestantDetail} returns this
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.prototype.setDiscordTag = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool is_student = 3;
 * @return {boolean}
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.prototype.getIsStudent = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.isuxportal.proto.resources.Contestant.ContestantDetail} returns this
 */
proto.isuxportal.proto.resources.Contestant.ContestantDetail.prototype.setIsStudent = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.isuxportal.proto.resources.Contestant.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.isuxportal.proto.resources.Contestant} returns this
 */
proto.isuxportal.proto.resources.Contestant.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 team_id = 2;
 * @return {number}
 */
proto.isuxportal.proto.resources.Contestant.prototype.getTeamId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.isuxportal.proto.resources.Contestant} returns this
 */
proto.isuxportal.proto.resources.Contestant.prototype.setTeamId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.isuxportal.proto.resources.Contestant.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.resources.Contestant} returns this
 */
proto.isuxportal.proto.resources.Contestant.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string avatar_url = 4;
 * @return {string}
 */
proto.isuxportal.proto.resources.Contestant.prototype.getAvatarUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.resources.Contestant} returns this
 */
proto.isuxportal.proto.resources.Contestant.prototype.setAvatarUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional ContestantDetail contestant_detail = 7;
 * @return {?proto.isuxportal.proto.resources.Contestant.ContestantDetail}
 */
proto.isuxportal.proto.resources.Contestant.prototype.getContestantDetail = function() {
  return /** @type{?proto.isuxportal.proto.resources.Contestant.ContestantDetail} */ (
    jspb.Message.getWrapperField(this, proto.isuxportal.proto.resources.Contestant.ContestantDetail, 7));
};


/**
 * @param {?proto.isuxportal.proto.resources.Contestant.ContestantDetail|undefined} value
 * @return {!proto.isuxportal.proto.resources.Contestant} returns this
*/
proto.isuxportal.proto.resources.Contestant.prototype.setContestantDetail = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.isuxportal.proto.resources.Contestant} returns this
 */
proto.isuxportal.proto.resources.Contestant.prototype.clearContestantDetail = function() {
  return this.setContestantDetail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.isuxportal.proto.resources.Contestant.prototype.hasContestantDetail = function() {
  return jspb.Message.getField(this, 7) != null;
};


goog.object.extend(exports, proto.isuxportal.proto.resources);
