# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/common/dashboard.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/common/dashboard.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.common.DashboardRequest" do
    end
    add_message "isuxportal.proto.common.DashboardResponse" do
    end
  end
end

module Isuxportal
  module Proto
    module Common
      DashboardRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.common.DashboardRequest").msgclass
      DashboardResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.common.DashboardResponse").msgclass
    end
  end
end
