# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/common/me.proto

require 'google/protobuf'

require 'isuxportal/resources/team_pb'
require 'isuxportal/resources/contestant_pb'
require 'isuxportal/resources/contestant_instance_pb'
require 'isuxportal/resources/contest_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/common/me.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.common.GetCurrentSessionRequest" do
    end
    add_message "isuxportal.proto.services.common.GetCurrentSessionResponse" do
      optional :team, :message, 1, "isuxportal.proto.resources.Team"
      optional :contestant, :message, 2, "isuxportal.proto.resources.Contestant"
      optional :discord_server_id, :string, 3
      optional :contest, :message, 4, "isuxportal.proto.resources.Contest"
      repeated :contestant_instances, :message, 5, "isuxportal.proto.resources.ContestantInstance"
      optional :push_vapid_key, :string, 6
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Common
        GetCurrentSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.common.GetCurrentSessionRequest").msgclass
        GetCurrentSessionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.common.GetCurrentSessionResponse").msgclass
      end
    end
  end
end
