// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: isuxportal/resources/env_check_status.proto

package resources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvCheckStatus int32

const (
	EnvCheckStatus_NOT_STARTED      EnvCheckStatus = 0
	EnvCheckStatus_CREATED_INSTANCE EnvCheckStatus = 1 // obtained instance ip successfully
	EnvCheckStatus_DONE             EnvCheckStatus = 2 // confirmed ssh
)

// Enum value maps for EnvCheckStatus.
var (
	EnvCheckStatus_name = map[int32]string{
		0: "NOT_STARTED",
		1: "CREATED_INSTANCE",
		2: "DONE",
	}
	EnvCheckStatus_value = map[string]int32{
		"NOT_STARTED":      0,
		"CREATED_INSTANCE": 1,
		"DONE":             2,
	}
)

func (x EnvCheckStatus) Enum() *EnvCheckStatus {
	p := new(EnvCheckStatus)
	*p = x
	return p
}

func (x EnvCheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvCheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_isuxportal_resources_env_check_status_proto_enumTypes[0].Descriptor()
}

func (EnvCheckStatus) Type() protoreflect.EnumType {
	return &file_isuxportal_resources_env_check_status_proto_enumTypes[0]
}

func (x EnvCheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvCheckStatus.Descriptor instead.
func (EnvCheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_isuxportal_resources_env_check_status_proto_rawDescGZIP(), []int{0}
}

var File_isuxportal_resources_env_check_status_proto protoreflect.FileDescriptor

var file_isuxportal_resources_env_check_status_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x69, 0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x65, 0x6e, 0x76, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x69,
	0x73, 0x75, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2a, 0x41, 0x0a, 0x0e, 0x45, 0x6e, 0x76,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x4e,
	0x4f, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x42, 0x41, 0x5a, 0x3f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x73, 0x75, 0x63, 0x6f,
	0x6e, 0x2f, 0x69, 0x73, 0x75, 0x63, 0x6f, 0x6e, 0x31, 0x30, 0x2d, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x6f, 0x2f, 0x69, 0x73, 0x75, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_isuxportal_resources_env_check_status_proto_rawDescOnce sync.Once
	file_isuxportal_resources_env_check_status_proto_rawDescData = file_isuxportal_resources_env_check_status_proto_rawDesc
)

func file_isuxportal_resources_env_check_status_proto_rawDescGZIP() []byte {
	file_isuxportal_resources_env_check_status_proto_rawDescOnce.Do(func() {
		file_isuxportal_resources_env_check_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_isuxportal_resources_env_check_status_proto_rawDescData)
	})
	return file_isuxportal_resources_env_check_status_proto_rawDescData
}

var file_isuxportal_resources_env_check_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_isuxportal_resources_env_check_status_proto_goTypes = []interface{}{
	(EnvCheckStatus)(0), // 0: isuxportal.proto.resources.EnvCheckStatus
}
var file_isuxportal_resources_env_check_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_isuxportal_resources_env_check_status_proto_init() }
func file_isuxportal_resources_env_check_status_proto_init() {
	if File_isuxportal_resources_env_check_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_isuxportal_resources_env_check_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isuxportal_resources_env_check_status_proto_goTypes,
		DependencyIndexes: file_isuxportal_resources_env_check_status_proto_depIdxs,
		EnumInfos:         file_isuxportal_resources_env_check_status_proto_enumTypes,
	}.Build()
	File_isuxportal_resources_env_check_status_proto = out.File
	file_isuxportal_resources_env_check_status_proto_rawDesc = nil
	file_isuxportal_resources_env_check_status_proto_goTypes = nil
	file_isuxportal_resources_env_check_status_proto_depIdxs = nil
}
