// source: services/registration/session.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var resources_team_pb = require('../../resources/team_pb.js');
goog.object.extend(proto, resources_team_pb);
goog.exportSymbol('proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest', null, global);
goog.exportSymbol('proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.displayName = 'proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.displayName = 'proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    inviteToken: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest;
  return proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInviteToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInviteToken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string invite_token = 1;
 * @return {string}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.prototype.getInviteToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest} returns this
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionRequest.prototype.setInviteToken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    team: (f = msg.getTeam()) && resources_team_pb.Team.toObject(includeInstance, f),
    ready: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    githubLogin: jspb.Message.getFieldWithDefault(msg, 3, ""),
    discordTag: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse;
  return proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new resources_team_pb.Team;
      reader.readMessage(value,resources_team_pb.Team.deserializeBinaryFromReader);
      msg.setTeam(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReady(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setGithubLogin(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscordTag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeam();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      resources_team_pb.Team.serializeBinaryToWriter
    );
  }
  f = message.getReady();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getGithubLogin();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDiscordTag();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional isuxportal.proto.resources.Team team = 1;
 * @return {?proto.isuxportal.proto.resources.Team}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.getTeam = function() {
  return /** @type{?proto.isuxportal.proto.resources.Team} */ (
    jspb.Message.getWrapperField(this, resources_team_pb.Team, 1));
};


/**
 * @param {?proto.isuxportal.proto.resources.Team|undefined} value
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse} returns this
*/
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.setTeam = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse} returns this
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.clearTeam = function() {
  return this.setTeam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.hasTeam = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool ready = 2;
 * @return {boolean}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.getReady = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse} returns this
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.setReady = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string github_login = 3;
 * @return {string}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.getGithubLogin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse} returns this
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.setGithubLogin = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string discord_tag = 4;
 * @return {string}
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.getDiscordTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse} returns this
 */
proto.isuxportal.proto.services.registration.GetRegistrationSessionResponse.prototype.setDiscordTag = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.isuxportal.proto.services.registration);
