// source: services/common/me.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var resources_team_pb = require('../../resources/team_pb.js');
goog.object.extend(proto, resources_team_pb);
var resources_contestant_pb = require('../../resources/contestant_pb.js');
goog.object.extend(proto, resources_contestant_pb);
goog.exportSymbol('proto.isuxportal.proto.services.common.GetCurrentSessionRequest', null, global);
goog.exportSymbol('proto.isuxportal.proto.services.common.GetCurrentSettionResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.services.common.GetCurrentSessionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.isuxportal.proto.services.common.GetCurrentSessionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.services.common.GetCurrentSessionRequest.displayName = 'proto.isuxportal.proto.services.common.GetCurrentSessionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.isuxportal.proto.services.common.GetCurrentSettionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.services.common.GetCurrentSettionResponse.displayName = 'proto.isuxportal.proto.services.common.GetCurrentSettionResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.services.common.GetCurrentSessionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.services.common.GetCurrentSessionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.services.common.GetCurrentSessionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.common.GetCurrentSessionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.services.common.GetCurrentSessionRequest}
 */
proto.isuxportal.proto.services.common.GetCurrentSessionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.services.common.GetCurrentSessionRequest;
  return proto.isuxportal.proto.services.common.GetCurrentSessionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.services.common.GetCurrentSessionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.services.common.GetCurrentSessionRequest}
 */
proto.isuxportal.proto.services.common.GetCurrentSessionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.services.common.GetCurrentSessionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.services.common.GetCurrentSessionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.services.common.GetCurrentSessionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.common.GetCurrentSessionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.services.common.GetCurrentSettionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    team: (f = msg.getTeam()) && resources_team_pb.Team.toObject(includeInstance, f),
    contestant: (f = msg.getContestant()) && resources_contestant_pb.Contestant.toObject(includeInstance, f),
    discordInvitationUrl: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse}
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.services.common.GetCurrentSettionResponse;
  return proto.isuxportal.proto.services.common.GetCurrentSettionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse}
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new resources_team_pb.Team;
      reader.readMessage(value,resources_team_pb.Team.deserializeBinaryFromReader);
      msg.setTeam(value);
      break;
    case 2:
      var value = new resources_contestant_pb.Contestant;
      reader.readMessage(value,resources_contestant_pb.Contestant.deserializeBinaryFromReader);
      msg.setContestant(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscordInvitationUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.services.common.GetCurrentSettionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeam();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      resources_team_pb.Team.serializeBinaryToWriter
    );
  }
  f = message.getContestant();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      resources_contestant_pb.Contestant.serializeBinaryToWriter
    );
  }
  f = message.getDiscordInvitationUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional isuxportal.proto.resources.Team team = 1;
 * @return {?proto.isuxportal.proto.resources.Team}
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.getTeam = function() {
  return /** @type{?proto.isuxportal.proto.resources.Team} */ (
    jspb.Message.getWrapperField(this, resources_team_pb.Team, 1));
};


/**
 * @param {?proto.isuxportal.proto.resources.Team|undefined} value
 * @return {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse} returns this
*/
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.setTeam = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse} returns this
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.clearTeam = function() {
  return this.setTeam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.hasTeam = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional isuxportal.proto.resources.Contestant contestant = 2;
 * @return {?proto.isuxportal.proto.resources.Contestant}
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.getContestant = function() {
  return /** @type{?proto.isuxportal.proto.resources.Contestant} */ (
    jspb.Message.getWrapperField(this, resources_contestant_pb.Contestant, 2));
};


/**
 * @param {?proto.isuxportal.proto.resources.Contestant|undefined} value
 * @return {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse} returns this
*/
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.setContestant = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse} returns this
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.clearContestant = function() {
  return this.setContestant(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.hasContestant = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string discord_invitation_url = 3;
 * @return {string}
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.getDiscordInvitationUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.services.common.GetCurrentSettionResponse} returns this
 */
proto.isuxportal.proto.services.common.GetCurrentSettionResponse.prototype.setDiscordInvitationUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.isuxportal.proto.services.common);
