# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/contestant/cloud_formation.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/contestant/cloud_formation.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.contestant.GetCloudFormationQuery" do
    end
    add_message "isuxportal.proto.services.contestant.GetCloudFormationResponse" do
      optional :template, :string, 1
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Contestant
        GetCloudFormationQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.GetCloudFormationQuery").msgclass
        GetCloudFormationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.GetCloudFormationResponse").msgclass
      end
    end
  end
end
