# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/contestant/instances.proto

require 'google/protobuf'

require 'isuxportal/resources/contestant_instance_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/contestant/instances.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.contestant.ListContestantInstancesRequest" do
    end
    add_message "isuxportal.proto.services.contestant.ListContestantInstancesResponse" do
      repeated :contestant_instances, :message, 1, "isuxportal.proto.resources.ContestantInstance"
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Contestant
        ListContestantInstancesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.ListContestantInstancesRequest").msgclass
        ListContestantInstancesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.ListContestantInstancesResponse").msgclass
      end
    end
  end
end
