# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/contestant/notification.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/contestant/notification.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.contestant.GetNotificationsRequest" do
    end
    add_message "isuxportal.proto.services.contestant.GetNotificationsResponse" do
      optional :last_answered_clarification_id, :int64, 1
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Contestant
        GetNotificationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.GetNotificationsRequest").msgclass
        GetNotificationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.GetNotificationsResponse").msgclass
      end
    end
  end
end
