# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/contestant/notifications.proto

require 'google/protobuf'

require 'isuxportal/resources/notification_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/contestant/notifications.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.contestant.ListNotificationsQuery" do
      optional :after, :int64, 1
    end
    add_message "isuxportal.proto.services.contestant.ListNotificationsResponse" do
      optional :last_answered_clarification_id, :int64, 1
      repeated :notifications, :message, 2, "isuxportal.proto.resources.Notification"
    end
    add_message "isuxportal.proto.services.contestant.SubscribeNotificationRequest" do
      optional :endpoint, :string, 1
      optional :p256dh, :string, 2
      optional :auth, :string, 3
    end
    add_message "isuxportal.proto.services.contestant.SubscribeNotificationResponse" do
    end
    add_message "isuxportal.proto.services.contestant.UnsubscribeNotificationRequest" do
      optional :endpoint, :string, 1
    end
    add_message "isuxportal.proto.services.contestant.UnsubscribeNotificationResponse" do
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Contestant
        ListNotificationsQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.ListNotificationsQuery").msgclass
        ListNotificationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.ListNotificationsResponse").msgclass
        SubscribeNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.SubscribeNotificationRequest").msgclass
        SubscribeNotificationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.SubscribeNotificationResponse").msgclass
        UnsubscribeNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.UnsubscribeNotificationRequest").msgclass
        UnsubscribeNotificationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.contestant.UnsubscribeNotificationResponse").msgclass
      end
    end
  end
end
