# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/dcim/instance_management.proto

require 'google/protobuf'

require 'isuxportal/resources/contestant_instance_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/dcim/instance_management.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.dcim.InformInstanceStateUpdateRequest" do
      optional :token, :string, 1
      optional :instance, :message, 2, "isuxportal.proto.resources.ContestantInstance"
    end
    add_message "isuxportal.proto.services.dcim.InformInstanceStateUpdateResponse" do
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Dcim
        InformInstanceStateUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.dcim.InformInstanceStateUpdateRequest").msgclass
        InformInstanceStateUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.dcim.InformInstanceStateUpdateResponse").msgclass
      end
    end
  end
end
