# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/misc/bot/support.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/misc/bot/support.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.misc.bot.SupportCommInfo" do
      optional :usage, :message, 2, "isuxportal.proto.misc.bot.SupportCommInfo.Usage"
    end
    add_message "isuxportal.proto.misc.bot.SupportCommInfo.Usage" do
      optional :message_id_since, :uint64, 1
      optional :team_id, :int64, 2
      optional :clarification_id, :int64, 3
    end
  end
end

module Isuxportal
  module Proto
    module Misc
      module Bot
        SupportCommInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.misc.bot.SupportCommInfo").msgclass
        SupportCommInfo::Usage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.misc.bot.SupportCommInfo.Usage").msgclass
      end
    end
  end
end
