source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
gem 'blouson'
gem 'revision_plate'

gem 'puma'
gem 'griffin'
gem 'griffin-interceptors'
gem 'grpc_kit', git: 'https://isucon10-public.s3.dualstack.ap-northeast-1.amazonaws.com/git/6MGgQp9lDmsK6G0CNa0DCOWHkOXID9-1davWxzKzI28/grpc_kit.git', ref: 'blocking-recv-buffer'
#gem 'grpc_kit', path: '~/git/github.com/cookpad/grpc_kit'
gem 'google-protobuf'
gem 'redis', require: ["redis", "redis/connection/hiredis"]
gem 'hiredis'
gem 'redis-actionpack' # session store
gem 'sentry-raven'
gem 'active_record_mysql_xverify'

gem 'shoryuken'
gem 'aws-sdk-sqs'

gem 'simpacker'

gem 'mysql2', '>= 0.4.4'

gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-discord'

gem 'addressable'

gem 'discordrb', git: 'https://github.com/discordrb/discordrb'
gem 'octokit'
gem 'webpush'

gem 'rack-timeout'
gem 'newrelic_rpm'
gem 'sigdump', require: 'sigdump/setup'

gem 'faker'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails',  '~> 4'
  gem 'factory_bot'
end

group :development do
  gem 'grpc-tools'
end
