source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6.1.6'
gem 'blouson'
gem 'revision_plate'

gem 'net-ftp'
gem 'puma'
gem 'griffin'
gem 'griffin-interceptors'
gem 'grpc_kit', '~> 0.5.1'
gem 'google-protobuf'
gem 'redis', require: ["redis", "redis/connection/hiredis"]
gem 'hiredis'
gem 'redis-actionpack' # session store
gem 'sentry-raven'
gem 'active_record_mysql_xverify'

gem 'shoryuken'
gem 'aws-sdk-sqs'

gem 'simpacker'

gem 'mysql2', '>= 0.5.4'

gem 'omniauth', '< 2.0.0'
gem 'omniauth-github'
gem 'omniauth-discord'

gem 'addressable'

gem 'discordrb', git: 'https://github.com/discordrb/discordrb'
gem 'octokit'
gem 'webpush'
gem 'aws-sdk-ec2'
gem 'listen'

gem 'rack-timeout'
gem 'newrelic_rpm'
gem 'sigdump', require: 'sigdump/setup'

gem 'faker'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails',  '~> 4'
  gem 'factory_bot'
end

group :development do
  gem 'grpc-tools'
end
