source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
gem 'blouson'
gem 'revision_plate'

gem 'puma'
gem 'griffin'
gem 'griffin-interceptors'

gem 'simpacker'

gem 'mysql2', '>= 0.4.4'

gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-discord'

gem 'addressable'

gem 'discordrb'
gem 'octokit'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails',  '~> 4'
end

group :development do
end
