# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/resources/contest.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/resources/contest.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.resources.Contest" do
      optional :registration_opens_at, :message, 1, "google.protobuf.Timestamp"
      optional :registration_closes_at, :message, 2, "google.protobuf.Timestamp"
      optional :starts_at, :message, 3, "google.protobuf.Timestamp"
      optional :freezes_at, :message, 4, "google.protobuf.Timestamp"
      optional :ends_at, :message, 5, "google.protobuf.Timestamp"
      optional :status, :enum, 6, "isuxportal.proto.resources.Contest.Status"
      optional :frozen, :bool, 7
    end
    add_enum "isuxportal.proto.resources.Contest.Status" do
      value :STANDBY, 0
      value :REGISTRATION, 1
      value :STARTED, 2
      value :FINISHED, 3
    end
  end
end

module Isuxportal
  module Proto
    module Resources
      Contest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Contest").msgclass
      Contest::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Contest.Status").enummodule
    end
  end
end
