# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/resources/coupon.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/resources/coupon.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.resources.Coupon" do
      optional :id, :int64, 1
      optional :team_id, :int64, 2
      optional :code, :string, 3
      optional :activate, :bool, 4
    end
  end
end

module Isuxportal
  module Proto
    module Resources
      Coupon = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Coupon").msgclass
    end
  end
end
