# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/resources/env_check.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/resources/env_check.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.resources.EnvCheck" do
      optional :id, :int64, 1
      optional :team_id, :int64, 2
      optional :name, :string, 3
      optional :ip_address, :string, 4
      optional :passed, :bool, 5
      optional :message, :string, 6
      optional :admin_message, :string, 7
      optional :raw_data, :string, 8
      optional :created_at, :message, 9, "google.protobuf.Timestamp"
      optional :updated_at, :message, 10, "google.protobuf.Timestamp"
    end
    add_enum "isuxportal.proto.resources.EnvCheckStatus" do
      value :NOT_STARTED, 0
      value :CREATED_INSTANCE, 1
      value :DONE, 2
    end
  end
end

module Isuxportal
  module Proto
    module Resources
      EnvCheck = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.EnvCheck").msgclass
      EnvCheckStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.EnvCheckStatus").enummodule
    end
  end
end
