# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/resources/env_check_status.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/resources/env_check_status.proto", :syntax => :proto3) do
    add_enum "isuxportal.proto.resources.EnvCheckStatus" do
      value :NOT_STARTED, 0
      value :CREATED_INSTANCE, 1
      value :DONE, 2
    end
  end
end

module Isuxportal
  module Proto
    module Resources
      EnvCheckStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.EnvCheckStatus").enummodule
    end
  end
end
