# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/resources/leaderboard.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'isuxportal/resources/team_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/resources/leaderboard.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.resources.Leaderboard" do
      repeated :teams, :message, 1, "isuxportal.proto.resources.Leaderboard.LeaderboardItem"
      repeated :general_teams, :message, 2, "isuxportal.proto.resources.Leaderboard.LeaderboardItem"
      repeated :student_teams, :message, 3, "isuxportal.proto.resources.Leaderboard.LeaderboardItem"
      repeated :progresses, :message, 4, "isuxportal.proto.resources.Leaderboard.LeaderboardItem"
      optional :frozen, :bool, 5
    end
    add_message "isuxportal.proto.resources.Leaderboard.LeaderboardItem" do
      repeated :scores, :message, 1, "isuxportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore"
      optional :team, :message, 16, "isuxportal.proto.resources.Team"
    end
    add_message "isuxportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore" do
      optional :score, :int64, 1
      optional :started_at, :message, 2, "google.protobuf.Timestamp"
      optional :updated_at, :message, 3, "google.protobuf.Timestamp"
    end
  end
end

module Isuxportal
  module Proto
    module Resources
      Leaderboard = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Leaderboard").msgclass
      Leaderboard::LeaderboardItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Leaderboard.LeaderboardItem").msgclass
      Leaderboard::LeaderboardItem::LeaderboardScore = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore").msgclass
    end
  end
end
