# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/resources/notification.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/resources/notification.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.resources.Notification" do
      optional :id, :int64, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      oneof :content do
        optional :content_benchmark_job, :message, 3, "isuxportal.proto.resources.Notification.BenchmarkJobMessage"
        optional :content_clarification, :message, 4, "isuxportal.proto.resources.Notification.ClarificationMessage"
        optional :content_test, :message, 5, "isuxportal.proto.resources.Notification.TestMessage"
      end
    end
    add_message "isuxportal.proto.resources.Notification.BenchmarkJobMessage" do
      optional :benchmark_job_id, :int64, 1
    end
    add_message "isuxportal.proto.resources.Notification.ClarificationMessage" do
      optional :clarification_id, :int64, 1
      optional :owned, :bool, 2
      optional :updated, :bool, 3
      optional :admin, :bool, 4
    end
    add_message "isuxportal.proto.resources.Notification.TestMessage" do
      optional :something, :int64, 1
    end
  end
end

module Isuxportal
  module Proto
    module Resources
      Notification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Notification").msgclass
      Notification::BenchmarkJobMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Notification.BenchmarkJobMessage").msgclass
      Notification::ClarificationMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Notification.ClarificationMessage").msgclass
      Notification::TestMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.Notification.TestMessage").msgclass
    end
  end
end
