# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/resources/survey_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/resources/survey_response.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.resources.SurveyResponse" do
      optional :language, :string, 1
    end
  end
end

module Isuxportal
  module Proto
    module Resources
      SurveyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.resources.SurveyResponse").msgclass
    end
  end
end
