// source: services/audience/team_list.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.isuxportal.proto.services.audience.ListTeamRequest', null, global);
goog.exportSymbol('proto.isuxportal.proto.services.audience.ListTeamResponse', null, global);
goog.exportSymbol('proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.services.audience.ListTeamRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.isuxportal.proto.services.audience.ListTeamRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.services.audience.ListTeamRequest.displayName = 'proto.isuxportal.proto.services.audience.ListTeamRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.services.audience.ListTeamResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.isuxportal.proto.services.audience.ListTeamResponse.repeatedFields_, null);
};
goog.inherits(proto.isuxportal.proto.services.audience.ListTeamResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.services.audience.ListTeamResponse.displayName = 'proto.isuxportal.proto.services.audience.ListTeamResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.repeatedFields_, null);
};
goog.inherits(proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.displayName = 'proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.services.audience.ListTeamRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.services.audience.ListTeamRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.services.audience.ListTeamRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.audience.ListTeamRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.services.audience.ListTeamRequest}
 */
proto.isuxportal.proto.services.audience.ListTeamRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.services.audience.ListTeamRequest;
  return proto.isuxportal.proto.services.audience.ListTeamRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.services.audience.ListTeamRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.services.audience.ListTeamRequest}
 */
proto.isuxportal.proto.services.audience.ListTeamRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.services.audience.ListTeamRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.services.audience.ListTeamRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.services.audience.ListTeamRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.audience.ListTeamRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.services.audience.ListTeamResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.services.audience.ListTeamResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    teamsList: jspb.Message.toObjectList(msg.getTeamsList(),
    proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.services.audience.ListTeamResponse;
  return proto.isuxportal.proto.services.audience.ListTeamResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.services.audience.ListTeamResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem;
      reader.readMessage(value,proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.deserializeBinaryFromReader);
      msg.addTeams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.services.audience.ListTeamResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.services.audience.ListTeamResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeamsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.toObject = function(opt_includeInstance) {
  return proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    teamId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    memberNamesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    finalParticipation: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem;
  return proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTeamId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addMemberNames(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFinalParticipation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeamId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMemberNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getFinalParticipation();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional int64 team_id = 1;
 * @return {number}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.getTeamId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem} returns this
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.setTeamId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem} returns this
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string member_names = 3;
 * @return {!Array<string>}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.getMemberNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem} returns this
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.setMemberNamesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem} returns this
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.addMemberNames = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem} returns this
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.clearMemberNamesList = function() {
  return this.setMemberNamesList([]);
};


/**
 * optional bool final_participation = 4;
 * @return {boolean}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.getFinalParticipation = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem} returns this
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem.prototype.setFinalParticipation = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * repeated TeamListItem teams = 1;
 * @return {!Array<!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem>}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.prototype.getTeamsList = function() {
  return /** @type{!Array<!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem, 1));
};


/**
 * @param {!Array<!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem>} value
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse} returns this
*/
proto.isuxportal.proto.services.audience.ListTeamResponse.prototype.setTeamsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem}
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.prototype.addTeams = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.isuxportal.proto.services.audience.ListTeamResponse.TeamListItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.isuxportal.proto.services.audience.ListTeamResponse} returns this
 */
proto.isuxportal.proto.services.audience.ListTeamResponse.prototype.clearTeamsList = function() {
  return this.setTeamsList([]);
};


goog.object.extend(exports, proto.isuxportal.proto.services.audience);
