# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/audience/dashboard.proto

require 'google/protobuf'

require 'isuxportal/resources/leaderboard_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/audience/dashboard.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.audience.DashboardQuery" do
    end
    add_message "isuxportal.proto.services.audience.DashboardResponse" do
      optional :leaderboard, :message, 1, "isuxportal.proto.resources.Leaderboard"
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Audience
        DashboardQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.audience.DashboardQuery").msgclass
        DashboardResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.audience.DashboardResponse").msgclass
      end
    end
  end
end
