# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/registration/activate_coupon.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/registration/activate_coupon.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.registration.ActivateCouponRequest" do
      optional :team_id, :int64, 1
    end
    add_message "isuxportal.proto.services.registration.ActivateCouponResponse" do
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Registration
        ActivateCouponRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.registration.ActivateCouponRequest").msgclass
        ActivateCouponResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.registration.ActivateCouponResponse").msgclass
      end
    end
  end
end
