# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/registration/create_team.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/registration/create_team.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.registration.CreateTeamRequest" do
      optional :team_name, :string, 1
      optional :name, :string, 2
      optional :email_address, :string, 3
      optional :is_student, :bool, 4
      optional :hidden, :bool, 16
    end
    add_message "isuxportal.proto.services.registration.CreateTeamResponse" do
      optional :team_id, :int64, 1
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Registration
        CreateTeamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.registration.CreateTeamRequest").msgclass
        CreateTeamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.registration.CreateTeamResponse").msgclass
      end
    end
  end
end
