# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/registration/env_check.proto

require 'google/protobuf'

require 'isuxportal/resources/env_check_status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/registration/env_check.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.registration.GetEnvCheckInformationResponse" do
      optional :template, :string, 1
      optional :status, :enum, 2, "isuxportal.proto.resources.EnvCheckStatus"
      optional :instance_ip, :string, 3
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Registration
        GetEnvCheckInformationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.registration.GetEnvCheckInformationResponse").msgclass
      end
    end
  end
end
