# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/registration/invite.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/registration/invite.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.registration.GetTeamInvitationRequest" do
    end
    add_message "isuxportal.proto.services.registration.GetTeamInvitationResponse" do
      optional :team_id, :int64, 1
      optional :invite_url, :string, 2
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Registration
        GetTeamInvitationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.registration.GetTeamInvitationRequest").msgclass
        GetTeamInvitationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.registration.GetTeamInvitationResponse").msgclass
      end
    end
  end
end
