name: supervisor
on:
  push:
    paths:
      - 'supervisor/**'
      - '.github/workflows/supervisor.yml'
    branches:
      - main

jobs:
  build:
    name: supervisor-build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: supervisor
    steps:
      - uses: actions/checkout@v2
      - run: 'echo $GITHUB_SHA > REVISION'

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          # https://github.com/actions-rs/cargo/issues/6
          args: --release --manifest-path supervisor/Cargo.toml

      - uses: actions/upload-artifact@v3
        with:
          name: isuxportal-supervisor-ubuntu2204-amd64
          path: supervisor/target/release/isuxportal-supervisor
